name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: 383265273024.dkr.ecr.us-east-1.amazonaws.com
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 383265273024.dkr.ecr.us-east-1.amazonaws.com:latest
    - name: Deploy to Kubernetes
      uses: Kubernetes/kubectl@v1.0.0
      with:
        args: apply -f deployment.yaml
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}


